name: Publish

on:
  workflow_dispatch:
  push:
    branches: ["master"]

jobs:
  time:
    runs-on: ubuntu-latest
    outputs:
      v: ${{ steps.date.outputs.time }}
      y: ${{ steps.date.outputs.y }}
      md: ${{ steps.date.outputs.md }}
      hm: ${{ steps.date.outputs.hm }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Time
        id: date
        run: |
          echo "::set-output name=time::$(date +'%Y.%m.%d.%H.%M')"
          echo "::set-output name=y::$(date +'%Y')"
          echo "::set-output name=md::$(date +'%m%d')"
          echo "::set-output name=hm::$(date +'%H%M')"
      - name: EchoTime
        run: |
          echo "The current time is: ${{ steps.date.outputs.time }}"

  linux:
    runs-on: ubuntu-20.04
    needs: time
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Dependency
        run: |
          dotnet tool install -g KuiperZone.PupNet
          sudo apt-get update
          sudo apt-get install fuse
      - name: Build-AppImage
        run: |
          cd ./Round.NET.AvaloniaApp.EncodeCalculator
          sudo su
          pupnet --runtime linux-x64 --kind appimage -o Round.NET.AvaloniaApp.EncodeCalculator.linux.x64.AppImage -y --app-version ${{ needs.time.outputs.y }}.${{ needs.time.outputs.md }}.${{ needs.time.outputs.hm }}
          pupnet --runtime linux-arm --kind appimage -o Round.NET.AvaloniaApp.EncodeCalculator.linux.arm.AppImage -y --app-version ${{ needs.time.outputs.y }}.${{ needs.time.outputs.md }}.${{ needs.time.outputs.hm }}
          pupnet --runtime linux-arm64 --kind appimage -o Round.NET.AvaloniaApp.EncodeCalculator.linux.arm64.AppImage -y --app-version ${{ needs.time.outputs.y }}.${{ needs.time.outputs.md }}.${{ needs.time.outputs.hm }}
      - name: Build-MacOsApp
        run: |
          cd ./Round.NET.AvaloniaApp.EncodeCalculator
          sudo su
          dotnet restore -r osx-x64
          dotnet msbuild -t:BundleApp -p:RuntimeIdentifier=osx-x64  -property:Configuration=Release -p:SelfContained=true
          dotnet restore -r osx-arm64
          dotnet msbuild -t:BundleApp -p:RuntimeIdentifier=osx-arm64  -property:Configuration=Release -p:SelfContained=true
          cd ./bin/Release/net8.0/
          cd ./osx-x64/publish/
          zip -9 -r ../../Round.NET.AvaloniaApp.EncodeCalculator.osx.mac.x64.app.zip ./Round.NET.AvaloniaApp.EncodeCalculator.app
          cd ../../
          cd ./osx-arm64/publish/
          zip -9 -r ../../Round.NET.AvaloniaApp.EncodeCalculator.osx.mac.arm64.app.zip ./Round.NET.AvaloniaApp.EncodeCalculator.app
      - name: Build-WinExe
        run: |
          cd ./Round.NET.AvaloniaApp.EncodeCalculator
          sudo su
          dotnet publish -r win-x86 --self-contained true -p:PublishSingleFile=true
          dotnet publish -r win-x64 --self-contained true -p:PublishSingleFile=true
          dotnet publish -r win-arm64 --self-contained true -p:PublishSingleFile=true
          mv ./bin/Release/net8.0/win-x86/publish/Round.NET.AvaloniaApp.EncodeCalculator.exe ./bin/Release/net8.0/win-x86/publish/Round.NET.AvaloniaApp.EncodeCalculator.win7.x86.exe
          mv ./bin/Release/net8.0/win-x64/publish/Round.NET.AvaloniaApp.EncodeCalculator.exe ./bin/Release/net8.0/win-x64/publish/Round.NET.AvaloniaApp.EncodeCalculator.win7.x64.exe
          mv ./bin/Release/net8.0/win-arm64/publish/Round.NET.AvaloniaApp.EncodeCalculator.exe ./bin/Release/net8.0/win-arm64/publish/Round.NET.AvaloniaApp.EncodeCalculator.win7.arm64.exe
          cd ./bin/Release/net8.0/
          cd ./win-x86/publish/
          zip -9 -r "../../Round.NET.AvaloniaApp.EncodeCalculator.win7.x86.exe.zip" "./Round.NET.AvaloniaApp.EncodeCalculator.win7.x86.exe"
          cd ../../
          cd ./win-x64/publish/
          zip -9 -r "../../Round.NET.AvaloniaApp.EncodeCalculator.win7.x64.exe.zip" "./Round.NET.AvaloniaApp.EncodeCalculator.win7.x64.exe"
          cd ../../
          cd ./win-arm64/publish/
          zip -9 -r "../../Round.NET.AvaloniaApp.EncodeCalculator.win7.arm64.exe.zip" "./Round.NET.AvaloniaApp.EncodeCalculator.win7.arm64.exe"
      - name: UploadArtifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-artifacts
          path: |
            Round.NET.AvaloniaApp.EncodeCalculator/Deploy/OUT/*
            Round.NET.AvaloniaApp.EncodeCalculator/bin/Release/net8.0/*.zip

  win:
    runs-on: windows-latest
    needs: time
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Dependency-InnoSetup
        uses: ConorMacBride/install-package@v1
        with:
          choco: innosetup
      - name: Chinesize-InnoSetup
        run: |
          Copy-Item "./Round.NET.AvaloniaApp.EncodeCalculator/Public/Texts/Default.isl" "C:\Program Files (x86)\Inno Setup 6\Default.isl" -Force
      - name: Dependency-Pupnet
        run: |
          dotnet tool install -g KuiperZone.PupNet
      - name: Time
        id: date
        run: |
          echo "${{ needs.time.outputs.v }}" > ./Round.NET.AvaloniaApp.EncodeCalculator/Public/Texts/DateTime.txt
          echo "Version is ${{ needs.time.outputs.v }}"
        shell: bash
      - name: Build
        run: |
          cd ./Round.NET.AvaloniaApp.EncodeCalculator
          pupnet -r win-x64 -k setup -y -o Round.NET.AvaloniaApp.EncodeCalculator.win.x64.installer.exe --app-version ${{ needs.time.outputs.y }}.${{ needs.time.outputs.md }}.${{ needs.time.outputs.hm }}
          pupnet -r win-x86 -k setup -y -o Round.NET.AvaloniaApp.EncodeCalculator.win.x86.installer.exe --app-version ${{ needs.time.outputs.y }}.${{ needs.time.outputs.md }}.${{ needs.time.outputs.hm }}
          pupnet -r win-arm64 -k setup -y -o Round.NET.AvaloniaApp.EncodeCalculator.win.arm64.installer.exe --app-version ${{ needs.time.outputs.y }}.${{ needs.time.outputs.md }}.${{ needs.time.outputs.hm }}
      - name: UploadArtifacts
        uses: actions/upload-artifact@v3
        with:
          name: win-artifacts
          path: |
            Round.NET.AvaloniaApp.EncodeCalculator/Deploy/OUT/*

  publish:
    needs: [linux, win, time]
    runs-on: ubuntu-latest
    steps:
      - name: Time
        id: gdate
        run: |
          echo "date=$(date +'%Y-%m-%d.%H-%M-%S')" >> $GITHUB_OUTPUT
          echo "title=$(date +'%Y.%m.%d.%H.%M')" >> $GITHUB_OUTPUT
      - name: Download-LinuxArtifacts
        uses: actions/download-artifact@v3
        with:
          name: linux-artifacts
          path: ./Round.NET.AvaloniaApp.EncodeCalculator.Release/
      - name: Download-WindowsArtifacts
        uses: actions/download-artifact@v3
        with:
          name: win-artifacts
          path: ./Round.NET.AvaloniaApp.EncodeCalculator.Release/
      - name: List Files
        run: |
          ls -la ./Round.NET.AvaloniaApp.EncodeCalculator.Release/
      - name: Publish Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.TOKEN }}"
          title: "v${{ needs.time.outputs.v }}"
          automatic_release_tag: "AutoPublish-${{ steps.gdate.outputs.date }}"
          prerelease: false
          files: |
            Round.NET.AvaloniaApp.EncodeCalculator.Release/*.exe
            Round.NET.AvaloniaApp.EncodeCalculator.Release/Deploy/OUT/*.AppImage
            Round.NET.AvaloniaApp.EncodeCalculator.Release/bin/Release/net8.0/*.zip
