name: Build Avalonia Desktop App

on:
  push:
    branches: [ "master" ]  # 修改为你使用的分支
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: 安装 .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  # 根据你的项目需求调整 .NET 版本

    - name: 构建
      run: dotnet build --configuration Release
